kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${TARGET_NAMESPACE}-admin-rolebinding
  namespace: ${TARGET_NAMESPACE}
subjects:
- kind: Group
  name: ${TARGET_NAMESPACE}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${TARGET_NAMESPACE}-kcm-admin-rolebinding
  namespace: ${TARGET_NAMESPACE}
subjects:
- kind: Group
  name: ${TARGET_NAMESPACE}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kcm-namespace-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-crd
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-listing-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${TARGET_NAMESPACE}-view-crd
subjects:
- kind: Group
  name: ${TARGET_NAMESPACE}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view-crd
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-listing-binding
subjects:
- kind: Group
  name: ${TARGET_NAMESPACE}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: namespace-listing-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${TARGET_NAMESPACE}-capi-manager
  namespace: ${TARGET_NAMESPACE}
subjects:
- kind: Group
  name: ${TARGET_NAMESPACE}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: capi-manager-role
  apiGroup: rbac.authorization.k8s.io
