apiVersion: k0rdent.mirantis.com/v1alpha1
kind: MultiClusterService
metadata:
  name: global-kyverno
spec:
  clusterSelector:
    matchLabels:
      k0rdent: demo
  serviceSpec:
    priority: 1000
    services:
      - template: demo-kyverno-3.2.6
        name: kyverno
        namespace: kyverno