apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: ${NAMESPACE}-aws-${CLUSTERNAME}
  namespace: ${NAMESPACE}
spec:
  template: demo-aws-standalone-cp-0.0.2
  credential: aws-cluster-identity-cred
  config:
    region: ${AWS_REGION}
    publicIP: true
    controlPlaneNumber: 1
    workersNumber: 2
    controlPlane:
      instanceType: t3.small
    worker:
      instanceType: t3.small