apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: demo-ingress-nginx-4.11.3
  namespace: ${NAMESPACE}
spec:
  helm:
    chartSpec:
      chart: demo-ingress-nginx
      version: 4.11.3
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-demos
---
apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplateChain
metadata:
  name: demo-ingress-nginx-4.11.3
  namespace: ${NAMESPACE}
spec:
  supportedTemplates:
    - name: demo-ingress-nginx-4.11.0
      availableUpgrades:
        - name: demo-ingress-nginx-4.11.3
    - name: demo-ingress-nginx-4.11.3