apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: demo-kyverno-3.2.6
  namespace: ${NAMESPACE}
spec:
  helm:
    chartSpec:
      chart: demo-kyverno
      version: 3.2.6
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: 2a-demos
---
apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplateChain
metadata:
  name: demo-kyverno-3.2.6
  namespace: ${NAMESPACE}
spec:
  supportedTemplates:
    - name: demo-kyverno-3.2.6