apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: ${NAMESPACE}-aws-${CLUSTERNAME}${UNIQUE_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: demo-aws-standalone-cp-0.0.2
  credential: aws-cluster-identity-cred
  config:
    region: ${AWS_REGION}
    publicIP: true
    clusterLabels:
      k0rdent: demo
    controlPlaneNumber: 1
    workersNumber: 2
    controlPlane:
      instanceType: t3.small
    worker:
      instanceType: t3.small
  serviceSpec:      
    services:
      - template: demo-ingress-nginx-4.11.0
        name: ingress-nginx
        namespace: ingress-nginx